"""Update Produk Model

Revision ID: bf79c07c3fdd
Revises: 530e1dd331f3
Create Date: 2023-10-28 18:47:46.594780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf79c07c3fdd'
down_revision = '530e1dd331f3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produk', 'created_at')
    op.drop_column('produk', 'updated_at')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('produk', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
